name: "Python Diff checker"
description: "Parse git diffs"
author: "SHAKOTN"
inputs:
  myInput:
    description: "Input to use"
    required: true
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
